theme: jekyll-theme-cayman

title: Lyndon的个人主页
description: >
  扎实的基础知识 + 优秀的工程能力 + 敏锐的业务理解 = 合格的算法工程师 
header-img: img/background.jpg
email: tanlingxiao123@163.com
url: https://tanligxiao.cn
SEOTitle: Lyndon的主页
keyword: 算法, 机器学习, 

github_username: TanLingxiao

paginate: 5

gems: [jekyll-paginate]


